spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mariadb://localhost:3306/microservice_products?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    discovery:
      enabled: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /index.html

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        security.web: DEBUG
        security.authentication: DEBUG
        security.authorization: DEBUG
        security.config: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      databaseService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        recordExceptions:
          - org.springframework.dao.DataAccessException
          - java.sql.SQLException

  timelimiter:
    instances:
      databaseService:
        timeoutDuration: 2s
        cancelRunningFuture: true

